# Generated by Django 5.1.6 on 2025-02-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='References',
            new_name='Reference',
        ),
    ]
