# Generated by Django 5.1.6 on 2025-02-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_church_alter_role_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='church',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='Church',
        ),
    ]
