# Generated by Django 5.1.6 on 2025-02-27 20:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_church_alter_role_church'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='church',
        ),
        migrations.RemoveField(
            model_name='role',
            name='job',
        ),
        migrations.CreateModel(
            name='ChurchRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.church')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.role')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.job')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.churchrole'),
        ),
    ]
